### ISSUE TITLE
need to add alias to hosts

### ISSUE THREAD

**Issue by majingshan** [isometry/alfred-ssh#1]
I used to use ssh many hosts, and I can't remember the ip(even a part of ip) of each host, so is there a way to add a alias to some frequently used host, so that I can search the host by alias instead of ip address.

**Comment by isometry** [comment]
You can add aliases to your ~/.ssh/config file, and they'll be picked up and matched by the workflow:

```
Host myalias1
  HostName real.hostname1.or.ip.address1

Host myalias2
  HostName real.hostname2.or.ip.address2

# etc.
```

See [ssh_config(5)](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5).

**Comment by majingshan** [comment]
I added the alias as you say, and my config looks like this
`Host myalias
  ip ssh-rsa base64-pubkey`
bug when I tried to search the host by alias, it doesn't appear on the list.

**Comment by isometry** [comment]
Recheck your syntax in the man page. The `Host` line should contain nothing but your alias(es); the associated `Hostname` line, and any other sub-stanzas should each be on a line if their own under the `Host` line. I don't believe your base64-pubkey has any reason to appear directly in `~/.ssh/config`

**Comment by majingshan** [comment]
Oh yes, it's my mistake, I add the config to ~/.ssh/known_hosts not ~/.ssh/config, and it works correctly now, thanks a lot.
