### ISSUE TITLE
Host with local ports forwarded

### ISSUE THREAD

**Issue by davidlfox** [isometry/alfred-ssh#2]
Possibly more of an SSH issue, but is it possible in ~/.ssh/known_hosts or ~/.ssh/config to get port forwarding picked up by this Alfred workflow? e.g.

    ssh -p 12345 host -L127.0.0.1:1234:192.168.1.1:1234

known_hosts picks up the port, but is there a way to enable the port forwarding?

**Comment by isometry** [comment]
David,

See [ssh_config(5)](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5). Add the following to your ~/.ssh/config:

```
Host host
  Port 12345
  LocalForward localhost:1234 192.168.1.1:1234
```

If you prefer to have connections to `host` without forwards by default, add an alias instead:

```
Host hostalias
  Hostname host
  Port 12345
  LocalForward localhost:1234 192.168.1.1:1234
```
