### ISSUE TITLE
iterm support

### ISSUE THREAD

**Issue by sampl3x** [isometry/alfred-ssh#5]
Is it possible that the workflow opens iterm instead of terminal?

**Comment by isometry** [comment]
Absolutely, yes! Simply configure iTerm to be your default ssh:// protocol handler:

Create a dedicated iTerm profile with:
* Name: `ssh-handler` (or whatever you prefer)
* Title: `User@Host` (automatically set the details of the host you connect to)
* Command: `$$` (automagic)
* Schemes Handled: `ssh` (the critical part)

**Comment by sampl3x** [comment]
Thank you that worked!!
