### ISSUE TITLE
Support for Warp

### ISSUE THREAD

**Issue by klaasgeldof** [isometry/alfred-ssh#6]
I would like to use [Warp](https://www.warp.dev/) as terminal, but can't make it work.

I can't select Warp as browser:

<img width="713" alt="CleanShot 2023-08-26 at 12 27 16@2x" src="https://github.com/isometry/alfred-ssh/assets/35819/289c5547-6be9-4043-8ea1-4c983c666b7e">

**Comment by isometry** [comment]
The workflow will open whatever program is currently registered to handle the `ssh:` protocol. As such, there's nothing I can do here: you need to ask the Warp developers to implement the appropriate handler (this was the first thing I looked for too, when kicking the tires on Warp last weekend …)
